### ISSUE TITLE
ANANSE network: KeyError: 'activity'

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#100]
command:
```
ananse network -g GRCz11.fa -a GRCz11.annotation.bed -n 12 -b binding_24hpf.tsv -e 24hpf_rep1.tsv 24hpf_rep2.tsv -o network_24hpf.txt
```

input:
```
$head -n 2 binding_24hpf.tsv
factor  enhancer        binding
SOX15   1:5842-6042     0.11866

$head -n 2 24hpf_rep1.tsv
gene_name       tpm
fam162a 19.823413000000002
```

full error message:
```
2021-06-29 18:14:58 | INFO | Loading expression
2021-06-29 18:18:00 | INFO | creating expression dataframe
2021-06-29 18:18:00 | INFO | Aggregate binding
2021-06-29 18:18:00 | INFO | reading enhancers
2021-06-29 18:20:47 | INFO | Reading binding file...
2021-06-29 18:20:50 | INFO | Grouping by tf and target gene...
2021-06-29 18:20:50 | INFO | Done grouping...
2021-06-29 18:20:50 | INFO | Reading factor activity
Traceback (most recent call last):
  File "/vol/mbconda/siebrenf/envs/ananse/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'activity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vol/mbconda/siebrenf/envs/ananse/bin/ananse", line 318, in <module>
    args.func(args)
  File "/vol/mbconda/siebrenf/envs/ananse/lib/python3.9/site-packages/ananse/commands/network.py", line 28, in network
    b.run_network(
  File "/vol/mbconda/siebrenf/envs/ananse/lib/python3.9/site-packages/ananse/network.py", line 558, in run_network
    act["activity"] = minmax_scale(rankdata(act["activity"], method="min"))
  File "/vol/mbconda/siebrenf/envs/ananse/lib/python3.9/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/vol/mbconda/siebrenf/envs/ananse/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'activity'
```

[responsible code ](https://github.com/vanheeringen-lab/ANANSE/blob/cd1f3fef7fcf486329a782748da8a099362fcf4f/ananse/network.py#L555)

I can't figure out where "factor_activity.tsv" is made. It must exist, but it seems to be missing a column.

**Comment by simonvh** [comment]
It's made when running `ananse binding`. Which version of ananse are you running? Can you try with the `develop` branch?

**Comment by siebrenf** [comment]
this was v0.2.2.

right, line 553: `activity_fname = binding.replace("binding.tsv", "factor_activity.tsv")` assumes binding is always named "binding.tsv". 
Now I don't get why `os.path.exists(activity_fname)` was `True`...

**Comment by siebrenf** [comment]
Rerunning network on develop makes no difference. 

I don't have "factor_activity.tsv", nor "binding.tsv" in my working directory.

**Comment by simonvh** [comment]
The output of `ananse binding` should be a directory. In that directory, there should be `binding.tsv` and ` factor_activity.tsv`?

However, `ananse network` should also work if it can't find `factor_activity` so I don't immediately see why it causes the error.

**Comment by simonvh** [comment]
This should also be fixed with the hdf file, as that contains the predicted factor activity.
