### ISSUE TITLE
bug in gimmemotifs(?)

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#11]
The following occurs when running `ananse binding` on Ensembl-aligned data. 
@simonvh is working on a fix. Posting it here for clarity.

```
Motif scanning
         0 - 10000 enhancers
2020-03-18 17:09:50,497 - INFO - using 10000 sequences
2020-03-18 17:09:50,497 - INFO - Creating index for genomic GC frequencies.
Traceback (most recent call last):
  File "/home/siebrenf/anaconda3/envs/ananse/bin/ananse", line 286, in <module>
    args.func(args)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/ananse/commands/binding.py", line 23, in binding
    a.run_binding(args.fin_rpkm, args.outfile)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 232, in run_binding
    pfm_weight = self.get_PWMScore(filter_bed)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 186, in get_PWMScore
    for seq, scores in zip(chunk_seqs, it):
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 872, in best_score
    for matches in self.scan(seqs, 1, scan_rc, zscore=zscore, gc=gc):
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 946, in scan
    self.set_meanstd(gc=gc)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 623, in set_meanstd
    self.set_background(gc=gc)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/gimmemotifs/scanner.py", line 747, in set_background
    tmp.name, genome, number=nseq, length=size, bins=gc_bins
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/gimmemotifs/background.py", line 387, in gc_bin_bedfile
    create_gc_bin_index(genome, fname, min_bin_size=min_bin_size)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/gimmemotifs/background.py", line 352, in create_gc_bin_index
    df.reset_index()[cols].to_feather(fname)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/pandas/core/frame.py", line 2152, in to_feather
    to_feather(self, fname)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/pandas/io/feather_format.py", line 66, in to_feather
    feather.write_feather(df, path)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/pyarrow/feather.py", line 183, in write_feather
    writer.write(df)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/pyarrow/feather.py", line 94, in write
    table = Table.from_pandas(df, preserve_index=False)
  File "pyarrow/table.pxi", line 1177, in pyarrow.lib.Table.from_pandas
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 580, in dataframe_to_arrays
    convert_fields))
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/siebrenf/anaconda3/envs/ananse/lib/python3.7/site-packages/pyarrow/pandas_compat.py", line 560, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 265, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 80, in pyarrow.lib._ndarray_to_array
TypeError: an integer is required (got type str)
```

**Comment by simonvh** [comment]
Fixed in gimmemotifs 0.14.4
