### ISSUE TITLE
ananse network error: TypeError: '<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by gscarnuntum** [vanheeringen-lab/ANANSE#114]
Error when running ananse network (v0.3.0):

`ananse binding -A GS691_4888_PI3K_OATAC_m1_filtered_nodups.bam -H GS784_4888_PI3K_H3K27ac_m1_filtered_nodups.bam -g mm10 -o PI3K.4888 -r multi_ATAC_complete_merged_pdac_dataset.bed -n 32`

generates binding.h5 file, but also gives error message:

```
2021-07-15 14:07:54 | INFO | No related TF found for Zfp809, using general model
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/anaconda3/envs/ananse/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/anaconda3/envs/ananse/lib/python3.9/runpy.py", line 268, in run_path
    main_content = runpy.run_path(main_path,
  File "/home/anaconda3/envs/ananse/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/anaconda3/envs/ananse/lib/python3.9/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "/home/anaconda3/envs/ananse/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,
  File "/home/anaconda3/envs/ananse/lib/python3.9/runpy.py", line 87, in _run_code
  File "/home/anaconda3/envs/ananse/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/ananse/bin/ananse", line 14, in <module>
    exec(code, run_globals)
  File "/home/anaconda3/envs/ananse/bin/ananse", line 14, in <module>
    from ananse import commands, __version__
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/__init__.py", line 1, in <module>
    from ananse import commands, __version__
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/__init__.py", line 1, in <module>
    from ananse.commands.binding import binding  # noqa
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/binding.py", line 7, in <module>
    from ananse.commands.binding import binding  # noqa
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/binding.py", line 7, in <module>
    from ananse.peakpredictor import predict_peaks
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 10, in <module>
    from ananse.peakpredictor import predict_peaks
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 10, in <module>
    from gimmemotifs.motif import read_motifs
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from gimmemotifs.motif import read_motifs
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/__init__.py", line 61, in <module>
    from . import denovo      # noqa: F401
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/denovo.py", line 51, in <module>
    from . import denovo      # noqa: F401
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/denovo.py", line 51, in <module>
    from gimmemotifs.stats import calc_stats, rank_motifs, write_stats
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/stats.py", line 10, in <module>
    from gimmemotifs.stats import calc_stats, rank_motifs, write_stats
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/stats.py", line 10, in <module>
    from gimmemotifs.scanner import scan_to_best_match, Scanner
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/scanner.py", line 58, in <module>
    from gimmemotifs.scanner import scan_to_best_match, Scanner
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/scanner.py", line 58, in <module>
    config = MotifConfig()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/config.py", line 95, in __init__
    config = MotifConfig()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/config.py", line 95, in __init__
    self._upgrade_config()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/config.py", line 98, in _upgrade_config
    self._upgrade_config()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/gimmemotifs/config.py", line 98, in _upgrade_config
    if "width" in self.config["params"]:
    if "width" in self.config["params"]:
  File "/home/anaconda3/envs/ananse/lib/python3.9/configparser.py", line 963, in __getitem__
  File "/home/anaconda3/envs/ananse/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'params'
    raise KeyError(key)
KeyError: 'params'
distributed.nanny - WARNING - Restarting worker
```
Then running ananse network:

`ananse network -b PI3K.4888/binding.h5 -e PI3K.4888.expression.txt -o PI3K.4888.network.mouse.txt -g mm10 -a mm10.gene.bed.txt`

```
2021-07-15 15:39:10 | INFO | Reading factor activity
2021-07-15 15:39:10 | INFO | Computing network
distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable-a64a741e-0bbd-4037-96f5-4c5a974b
args:      (               tf         target  ... target_expression  activity
0          Ahctf1  0610005C13Rik  ...          0.000000  0.255579
1          Ahctf1  0610006L08Rik  ...          0.000000  0.255579
2          Ahctf1  0610009B22Rik  ...          0.866266  0.255579
3          Ahctf1  0610009E02Rik  ...          0.321027  0.255579
4          Ahctf1  0610009L18Rik  ...          0.404860  0.255579
...           ...            ...  ...               ...       ...
19526767  Zscan4c           None  ...          0.490446  0.056323
19526768  Zscan4c           None  ...          0.000000  0.056323
19526769  Zscan4c           None  ...          0.000000  0.056323
19526770  Zscan4c           None  ...          0.000000  0.056323
19526771  Zscan4c           None  ...          0.504057  0.056323

[19526772 rows x 6 columns])
kwargs:    {}
Exception: TypeError("'<' not supported between instances of 'str' and 'float'")

Traceback (most recent call last):
  File "/home/anaconda3/envs/ananse/bin/ananse", line 369, in <module>
    args.func(args)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/network.py", line 46, in network
    b.run_network(
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/ananse/network.py", line 673, in run_network
    result = result.compute()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/base.py", line 286, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/base.py", line 568, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/client.py", line 2704, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/client.py", line 2018, in gather
    return self.sync(
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/client.py", line 859, in sync
    return sync(
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/client.py", line 1883, in _gather
    raise exception.with_traceback(traceback)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/optimization.py", line 969, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/utils.py", line 35, in apply
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/dataframe/core.py", line 5775, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/dask/dataframe/shuffle.py", line 757, in set_partitions_pre
    partitions[not_null] = divisions.searchsorted(s[not_null], side="right") - 1
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/pandas/core/series.py", line 2609, in searchsorted
    return algorithms.searchsorted(self._values, value, side=side, sorter=sorter)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/pandas/core/algorithms.py", line 1908, in searchsorted
    result = arr.searchsorted(value, side=side, sorter=sorter)
TypeError: '<' not supported between instances of 'str' and 'float'
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 5054, in add_client
    self.remove_client(client=client)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 5081, in remove_client
    self.client_releases_keys(
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 4821, in client_releases_keys
    self.transitions(recommendations)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 6753, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 5335, in send_all
    w = stream_comms[worker]
KeyError: 'tcp://127.0.0.1:38921'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x2ad8ac229550>, <Task finished name='Task-42' coro=<BaseTCPListener._handle_stream() done, defined at /home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/comm/tcp.py:473> exception=KeyError('tcp://127.0.0.1:38921')>)
Traceback (most recent call last):
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/comm/tcp.py", line 490, in _handle_stream
    await self.comm_handler(comm)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 5054, in add_client
    self.remove_client(client=client)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 5081, in remove_client
    self.client_releases_keys(
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 4821, in client_releases_keys
    self.transitions(recommendations)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 6753, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/home/anaconda3/envs/ananse/lib/python3.9/site-packages/distributed/scheduler.py", line 5335, in send_all
    w = stream_comms[worker]
KeyError: 'tcp://127.0.0.1:38921'
```

Interestingly no error was observed for human dataset, so seems to be somehow specific to handling mouse data. Mouse genome annotation was installed with genomepy. mm10.gene.bed file was downloaded from ananse github.

**Comment by simonvh** [comment]
Hmm.. The first error in `ananse binding` is a bug in GImmeMotifs (which is used by ANANSE). We will shortly release a fix. Looks like the command finished succesfully though.

For the other error, that is a new one. From your output it seems to be related to a `None` for a target gene, which suggest it's not the `binding.h5` that's at fault (that only contains TFs). Would you be able to post your expression file? And can you double check what happens if you use this annotation file? 

[mm10.annotation.name.bed.gz](https://github.com/vanheeringen-lab/ANANSE/files/6828701/mm10.annotation.name.bed.gz)

**Comment by gscarnuntum** [comment]
Thank you for the help. The problem was indeed the expression file which contained some lines with NA gene symbols. 
Actually, since we are using 3'RNA-seq we don't generate TPM values, but rather Deseq2 normalized values. Do you think this affects the analysis?

**Comment by simonvh** [comment]
Ah, that is good to know. This is something we can check for in a future version.

No, this will be fine. I guess the general distribution will be somewhat similar, and ANANSE ranks and scales the values anyway.

**Comment by gscarnuntum** [comment]
Great. Thanks!
