### ISSUE TITLE
ANANSE network AttributeError: module 'pandas' has no attribute 'Dataframe'

### ISSUE THREAD

**Issue by apposada** [vanheeringen-lab/ANANSE#125]
Hi all,

I am using a pip installation of ANANSE on a Centos 7 machine, from within a python 3.6.8 venv. Ananse Binding worked well and yielded no problems, but I got the following when subsequently running the network step (attaching the error plus a few lines prior for context):

```2021-09-01 10:05:43 | INFO | Aggregating binding for genes on Scaffold_129_1_contigs
Aggregating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 445/445 [00:07<00:00, 61.6 TFs/s]
2021-09-01 10:05:51 | INFO | Aggregating binding for genes on Scaffold_12_1_contigs
Aggregating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 445/445 [00:07<00:00, 61.5 TFs/s]
2021-09-01 10:06:03 | INFO | Aggregating binding for genes on Scaffold_130_1_contigs
2021-09-01 10:06:03 | ERROR | An error has been caught in function '<module>', process 'MainProcess' (24328), thread 'MainThread' (139758754117440):
Traceback (most recent call last):

> File "/home/user/path/to_ananse/ananse/ananse_pip_venv/bin/ananse", line 370, in <module>
    args.func(args)
    │    │    └ Namespace(annotation='annot/annot_longest.bed12.bed', binding='20210831_EB_binding/binding.h5', fin_expression=['rna/0...
    │    └ <function network at 0x7f1bb51f70d0>
    └ Namespace(annotation='annot/annot_longest.bed12.bed', binding='20210831_EB_binding/binding.h5', fin_expression=['rna/0...
  File "/home/user/path/to_ananse/ananse/ananse_pip_venv/lib64/python3.6/site-packages/ananse/commands/network.py", line 51, in network
    outfile=check_path(args.outfile, error_missing=False),
            │          │    └ '20210901_EB.network'
            │          └ Namespace(annotation='annot/annot_longest.bed12.bed', binding='20210831_EB_binding/binding.h5', fin_expression=['rna/0...
            └ <function check_path at 0x7f1bb78191e0>
  File "/home/user/path/to_ananse/ananse/ananse_pip_venv/lib64/python3.6/site-packages/ananse/network.py", line 651, in run_network
    combine_function="sum",
  File "/home/user/path/to_ananse/ananse/ananse_pip_venv/lib64/python3.6/site-packages/ananse/network.py", line 417, in aggregate_binding
    full_weight_region=full_weight_region,
                       └ 5000
  File "/home/user/path/to_ananse/ananse/ananse_pip_venv/lib64/python3.6/site-packages/ananse/network.py", line 265, in enhancer2gene
    return pd.Dataframe()
           └ <module 'pandas' from '/home/user/path/to_ananse/ananse/ananse_pip_venv/lib64/python3.6/site-packages/pandas/__init_...

AttributeError: module 'pandas' has no attribute 'Dataframe'
```

Please let me know if I can further help with anything.

Thanks and all the best!

**Comment by simonvh** [comment]
That... is a very weird one. Could it be related to the issue here, last comment on the page: https://stackoverflow.com/questions/20621607/module-object-has-no-attribute-dataframe

**Comment by Maarten-vd-Sande** [comment]
> For me he problem was that my script was called pandas.py in the folder pandas which obviously messed up my imports.

Do you happen to have a pandas.py file laying around? :thinking:

**Comment by apposada** [comment]
That's strange. There are two pandas.py files in my virtual environment's dependency directories:
./ananse_pip_venv/lib/python3.6/site-packages/statsmodels/compat/pandas.py
./ananse_pip_venv/lib/python3.6/site-packages/partd/pandas.py

Could it be because my ananse installation is done in pip?

**Comment by Maarten-vd-Sande** [comment]
Not sure if you actually have pandas installed. How did you install ananse?

**Comment by apposada** [comment]
I actually do have it:
```
(ananse_pip_venv) [aperpos@nodos ananse]$ find ananse_pip_venv/lib/python3.6/site-packages/ -name pandas
ananse_pip_venv/lib/python3.6/site-packages/pandas
```

I tried to install it in any case, and I got a 'Requirement satisfied' in return:
```
(ananse_pip_venv) [aperpos@nodos ananse]$ pip install pandas
Requirement already satisfied: pandas in ./ananse_pip_venv/lib/python3.6/site-packages (1.1.5)
Requirement already satisfied: python-dateutil>=2.7.3 in ./ananse_pip_venv/lib/python3.6/site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in ./ananse_pip_venv/lib/python3.6/site-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in ./ananse_pip_venv/lib/python3.6/site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in ./ananse_pip_venv/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
WARNING: You are using pip version 21.1.2; however, version 21.2.4 is available.
You should consider upgrading via the '/home/ska/aperpos/Def_Pfla/outputs/ananse/ananse_pip_venv/bin/python3 -m pip install --upgrade pip' command.
(ananse_pip_venv) [aperpos@nodos ananse]$ 
```

**Comment by Maarten-vd-Sande** [comment]
can you remove the `ananse_pip_venv/lib/python3.6/site-packages/pandas/__pycache__` folder and if you have a `__pycache__` folder in your cwd as well, and then try again?

**Comment by apposada** [comment]
I tried deleting that directory (and I didn't have any at my current working directory), and after that I've run it again. But I get the same error at the same step, after the same number of contigs.

**Comment by Maarten-vd-Sande** [comment]
Hmm not sure. Can you try with a fresh environment? I'm running out of ideas here :scream:

**Comment by apposada** [comment]
Based on my former experience installing ANANSE, where I am asked for several dependencies, I did a fresh installation using:
```
python3 -m venv ./ananse_pip_venv/
source ananse_pip_venv/bin/activate
pip install --upgrade pip
pip install cython
pip install pyarrow
pip install git+https://github.com/vanheeringen-lab/ANANSE.git@develop
python -m pip install 'fsspec>=0.3.3'
python -m pip install "dask[distributed]" --upgrade
```
And then re-launched my command:
```
ananse network -n 4 -b 20210831_EB_binding/binding.h5 -e rna/02_EB_02.tsv -g genome/ptyFlav3.fa -a annot/ptyFlav3_CYi_longest.bed12.bed -o 20210901_EB.network
```
And, to my dismay, it still showed the same error at the same step.

**Comment by apposada** [comment]
I believe this was a mispelling issue. Apparently it managed to finish properly when I substituted 'Dataframe' for 'DataFrame' (with upper case) on the network.py script. I am puzzled as I cannot find this line in the network.py here on GitHub, but my installation had it like that.

Still, thanks a lot for your time!

**Comment by Maarten-vd-Sande** [comment]
🤯

**Comment by Maarten-vd-Sande** [comment]
https://github.com/vanheeringen-lab/ANANSE/blob/develop/ananse/network.py#L265

It actually exists here ☝️

**Comment by hamzashabbir11** [comment]
> > For me he problem was that my script was called pandas.py in the folder pandas which obviously messed up my imports.
> 
> Do you happen to have a pandas.py file laying around? 🤔

>Issue Solved Thank You
