### ISSUE TITLE
Man_whitney_U test 

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/ANANSE#145]
For certain TFs the man-whitney u test fails with a RecursionError:

E.g: 

```
2021-10-06 14:54:28 | INFO | Reading network(s), using the union of the top 500000 edges of each GRN.
2021-10-06 15:00:25 | INFO | calculating diff GRN with full output
2021-10-06 15:00:31 | INFO | Differential network has 330492 edges.
2021-10-06 15:00:32 | INFO | Saving differential network.
2021-10-06 15:00:32 | INFO | output full diff network
2021-10-06 15:00:36 | INFO | Calculating target scores.
2021-10-06 15:00:36 | INFO | Differential network contains 120 transcription factors.
2021-10-06 15:00:36 | INFO | Out of these, 74 are differentially expressed.

  0%|          | 0/74 [00:00<?, ?it/s]2021-10-06 15:00:52 | WARNING | Could not calculate p-val (target vs non-target fold-change) for PAX6, targets = 6, non-target = 12812.

  1%|▏         | 1/74 [00:33<40:10, 33.01s/it]2021-10-06 15:01:16 | WARNING | Could not calculate p-val (target vs non-target fold-change) for EGR1, targets = 6, non-target = 12812.
2021-10-06 15:03:41 | WARNING | Could not calculate p-val (target vs non-target fold-change) for XBP1, targets = 2, non-target = 12816.
2021-10-06 15:03:51 | WARNING | Could not calculate p-val (target vs non-target fold-change) for SREBF1, targets = 4, non-target = 12814.
2021-10-06 15:09:11 | WARNING | Could not calculate p-val (target vs non-target fold-change) for MAFG, targets = 2, non-target = 12816.

  3%|▎         | 2/74 [10:10<7:04:07, 353.44s/it]
  4%|▍         | 3/74 [10:10<3:47:23, 192.16s/it]2021-10-06 15:11:31 | WARNING | Could not calculate p-val (target vs non-target fold-change) for FOXN3, targets = 3, non-target = 12815.
2021-10-06 15:11:56 | WARNING | Could not calculate p-val (target vs non-target fold-change) for HBP1, targets = 1, non-target = 12817.

 24%|██▍       | 18/74 [11:21<20:37, 22.11s/it]  
 34%|███▍      | 25/74 [13:13<16:09, 19.78s/it]
 35%|███▌      | 26/74 [13:15<14:49, 18.53s/it]
 41%|████      | 30/74 [15:15<15:59, 21.81s/it]
 43%|████▎     | 32/74 [15:41<14:14, 20.34s/it]2021-10-06 15:19:29 | WARNING | Could not calculate p-val (target vs non-target fold-change) for PBX2, targets = 5, non-target = 12813.

 45%|████▍     | 33/74 [19:02<27:23, 40.09s/it]2021-10-06 15:19:58 | WARNING | Could not calculate p-val (target vs non-target fold-change) for USF1, targets = 1, non-target = 12817.

 47%|████▋     | 35/74 [19:51<23:38, 36.37s/it]
 49%|████▊     | 36/74 [20:20<22:18, 35.22s/it]
 64%|██████▎   | 47/74 [21:52<07:28, 16.60s/it]
 68%|██████▊   | 50/74 [22:34<06:24, 16.03s/it]
 73%|███████▎  | 54/74 [23:09<04:37, 13.89s/it]2021-10-06 15:24:30 | WARNING | Could not calculate p-val (target vs non-target fold-change) for ZFHX3, targets = 1, non-target = 12817.

 78%|███████▊  | 58/74 [26:45<06:49, 25.62s/it]
 84%|████████▍ | 62/74 [28:35<05:14, 26.18s/it]
100%|██████████| 74/74 [28:35<00:00, 23.18s/it]
2021-10-06 15:29:14 | INFO | Calculating influence scores.

```

For some pseudobulk data it completely crashes with an ValueError:

```
2021-10-06 16:50:58 | INFO | Reading network(s), using the union of the top 500000 edges of each GRN.
2021-10-06 16:56:10 | INFO | calculating diff GRN with full output
2021-10-06 16:56:16 | INFO | Differential network has 328423 edges.
2021-10-06 16:56:18 | INFO | Saving differential network.
2021-10-06 16:56:18 | INFO | output full diff network
2021-10-06 16:56:21 | INFO | Calculating target scores.
2021-10-06 16:56:21 | INFO | Differential network contains 116 transcription factors.
2021-10-06 16:56:21 | INFO | Out of these, 46 are differentially expressed.

  0%|          | 0/46 [00:00<?, ?it/s]
  2%|▏         | 1/46 [03:45<2:49:13, 225.63s/it]
  4%|▍         | 2/46 [04:25<1:25:14, 116.23s/it]
  7%|▋         | 3/46 [16:12<4:36:51, 386.31s/it]
  9%|▊         | 4/46 [16:19<2:45:21, 236.23s/it]
  9%|▊         | 4/46 [16:19<2:51:21, 244.79s/it]
2021-10-06 17:12:40 | ERROR | An error has been caught in function '<module>', process 'MainProcess' (3339681), thread 'MainThread' (22969731467072):
Traceback (most recent call last):

  File "/vol/mbconda/jsmits/envs/ananse_dev/bin/ananse", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
                 │ │       └ '/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/scripts/ananse'
                 │ └ <method 'read' of '_io.TextIOWrapper' objects>
                 └ <_io.TextIOWrapper name='/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/scripts/ananse' mode='r' encoding='UTF-8'>
> File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/scripts/ananse", line 480, in <module>
    args.func(args)
    │    │    └ Namespace(GRN_target_file='/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Ananse_test_data/analysis/peakpred_V6/both/KCs_invivo/f...
    │    └ <function influence at 0x14e1fcbc05e0>
    └ Namespace(GRN_target_file='/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Ananse_test_data/analysis/peakpred_V6/both/KCs_invivo/f...

  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/ananse/commands/influence.py", line 31, in influence
    a.run_influence()
    │ └ <function Influence.run_influence at 0x14e1fcbc08b0>
    └ <ananse.influence.Influence object at 0x14e1fc22c9d0>

  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/ananse/influence.py", line 590, in run_influence
    influence_file = self.run_target_score()
                     │    └ <function Influence.run_target_score at 0x14e1fcbc0790>
                     └ <ananse.influence.Influence object at 0x14e1fc22c9d0>

  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/ananse/influence.py", line 502, in run_target_score
    targetScore(tf, self.G, self.expression_change, max_degree)
    │           │   │    │  │    │                  └ 3
    │           │   │    │  │    └ {'A1BG': Expression(score=0.0, absfc=0.7337573161721259, realfc=-0.7337573161721259), 'A1BG-AS1': Expression(score=0.0, absfc...
    │           │   │    │  └ <ananse.influence.Influence object at 0x14e1fc22c9d0>
    │           │   │    └ <networkx.classes.digraph.DiGraph object at 0x14e206b32ca0>
    │           │   └ <ananse.influence.Influence object at 0x14e1fc22c9d0>
    │           └ 'MAFB'
    └ <function targetScore at 0x14e1fcbc04c0>

  File "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/ANANSE/ananse/influence.py", line 297, in targetScore
    pval = mannwhitneyu(target_fc, non_target_fc)[1]
           │            │          └ [0.131746556188323, 0.52496808798771, 3.0844068233123303, 7.50127697680256, 2.1842018902670204, 0.0776501410922978, 0.3938122...
           │            └ []
           └ <function mannwhitneyu at 0x14e35f21f940>

  File "/vol/mbconda/jsmits/envs/ananse_dev/lib/python3.9/site-packages/scipy/stats/_mannwhitneyu.py", line 391, in mannwhitneyu
    _mwu_input_validation(x, y, use_continuity, alternative, axis, method))
    │                     │  │  │               │            │     └ 'auto'
    │                     │  │  │               │            └ 0
    │                     │  │  │               └ 'two-sided'
    │                     │  │  └ True
    │                     │  └ [0.131746556188323, 0.52496808798771, 3.0844068233123303, 7.50127697680256, 2.1842018902670204, 0.0776501410922978, 0.3938122...
    │                     └ []
    └ <function _mwu_input_validation at 0x14e35f21f3a0>
  File "/vol/mbconda/jsmits/envs/ananse_dev/lib/python3.9/site-packages/scipy/stats/_mannwhitneyu.py", line 135, in _mwu_input_validation
    raise ValueError('`x` and `y` must be of nonzero size.')

ValueError: `x` and `y` must be of nonzero size.
```

**Comment by simonvh** [comment]
See #123

**Comment by Maarten-vd-Sande** [comment]
Based on the error it seems that either is empty

**Comment by Maarten-vd-Sande** [comment]
Issue #123 is a recursionarray. That's different from this one I think
