### ISSUE TITLE
length of index

### ISSUE THREAD

**Issue by fmarletaz** [vanheeringen-lab/ANANSE#193]
Hi - 
Thanks for developping great tools! I am trying to run ANANSE on a new species with custom genome and annotation. I have an error during the binding stage that seems related to the read of my region bed file (see below). Any idea what the problem could be?  Thanks a lot! 
```
2022-10-22 12:59:11 | INFO | loading ATAC data
Traceback (most recent call last):
  File "/home/ferdi/miniconda3/envs/ananse/bin/ananse", line 369, in <module>
    args.func(args)
  File "/home/ferdi/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/binding.py", line 12, in binding
    predict_peaks(
  File "/home/ferdi/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 751, in predict_peaks
    p = PeakPredictor(
  File "/home/ferdi/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 99, in __init__
    self.load_atac(atac_bams, update_models=False)
  File "/home/ferdi/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 390, in load_atac
    self._atac_data = self._load_bams(bams, title="ATAC", window=200)
  File "/home/ferdi/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 344, in _load_bams
    tmp[result[0]] = result[2].T[0]
  File "/home/ferdi/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3655, in __setitem__
    self._set_item(key, value)
  File "/home/ferdi/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3832, in _set_item
    value = self._sanitize_column(value)
  File "/home/ferdi/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 4535, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/home/ferdi/.local/lib/python3.9/site-packages/pandas/core/common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (64687) does not match length of index (64701)
```

**Comment by siebrenf** [comment]
Hey Ferdinand, 

This issue was fixed in ANANSE 0.4. Try updating! :)

**Comment by fmarletaz** [comment]
Hi Siebren, 
Thanks for the tip, it worked and I successfully ran the `ananse binding`. 
I am encountering new errors in the `network` phrase: 
```

**Comment by siebrenf** [comment]
Hey again @fmarletaz,

The short answer: I think so.
The long answer: during ananse network we compute scores for _every_ transcription factor-gene pair and put that all in one dataframe. That's a lot of rows, so we use `dask` to manage CPU and RAM usage. This error comes from dask, but I haven't seen that one before! Since the output file is written, I think this is dask stopping its last processes.

Do you have more logs?

**Comment by fmarletaz** [comment]
Thanks for your reply, please find the full log attached. 
[ans_prism_network.log](https://github.com/vanheeringen-lab/ANANSE/files/10005154/ans_prism_network.log)
I now realised, I had more serious errors where the files were not written, like the one below: 
[ans_lateblastula_network.log](https://github.com/vanheeringen-lab/ANANSE/files/10005281/ans_lateblastula_network.log)
Thanks!

**Comment by siebrenf** [comment]
Those logs are empty :(

**Comment by fmarletaz** [comment]
Really sorry, here they are: 
[ans_lateblastula_network.log](https://github.com/vanheeringen-lab/ANANSE/files/10023927/ans_lateblastula_network.log)
[ans_prism_network.log](https://github.com/vanheeringen-lab/ANANSE/files/10023928/ans_prism_network.log)

**Comment by siebrenf** [comment]
(I've been trying to run this step with my own data, to see if I get a similar error, but I'll need a bit more time. Sorry for the delay.)

OK, so here is the big problem with ANANSE network: scores are generated for each TF-gene combination. That's a very big table, and it eats RAM. The error message is a mystery, but I think dask runs out of memory at the final merge step.

There are two thing you can try:
- run network with fewer cores
- try the develop branch. I _think_ it's slightly better with memory usage 

you can install the develop branch with
```
pip install git+https://github.com/vanheeringen-lab/ANANSE.git@develop
```

**Comment by fmarletaz** [comment]
Thanks a lot, I used a restricted set of peaks and it worked better!
I will try the newer branck!

Ferdi
