### ISSUE TITLE
ananse binding error

### ISSUE THREAD

**Issue by mr-ibrahim-ahmed** [vanheeringen-lab/ANANSE#24]
When running `ananse binding`, the following error occurs:

```
2020-06-17 16:30:06.413 | INFO     | ananse.binding:run_binding:250 - Peak initialization
Traceback (most recent call last):
  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/bin/ananse", line 326, in <module>
    args.func(args)

  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/lib/python3.7/site-packages/ananse/commands/binding.py", line 28, in binding
    a.run_binding(args.fin_rpkm, args.outfile)

  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 252, in run_binding
    filter_bed = self.set_peak_size(peak_bed)

  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 132, in set_peak_size
    if start > 0 and end < gsizedic[peak.chrom]:
TypeError: '<' not supported between instances of 'int' and 'str'
```
The enhancer BED file scores have been generated using deepTools `computeMatrix`

The genome has been installed with `genomepy` and I have updated to the latest version of ANANSE.

What could be causing this? Thank you.

**Comment by simonvh** [comment]
@mr-ibrahim-ahmed I found one important parameter that should be added to `computeMatrix` which is `--missingDataAsZero`. Otherwise `nan` will be used instead of 0.  However, it looks like your start or end of the BED file is not a number. Can you post the `head` and the `tail` of your BED?

The full `computerMatrix` command will look like this:

```
computeMatrix scale-regions -R <peaks.bed> -S <EP300.bw> -o tmp.txt.gz -m 200 -bs 200 --averageTypeBins max --missingDataAsZero
zcat tmp.txt.gz |tail -n+2 |cut -f1,2,3,7 > enhancer_signal.bed
```

I have also updated the docs at https://anansepy.readthedocs.io/en/master/input_data/

**Comment by mr-ibrahim-ahmed** [comment]
@simonvh Dear Simon, thanks for your response. I did use the `--missingDataAsZero` parameter.

The `head` of the BED file is:

```
chr1    125179805       125180426       8.605480
chr16   63613690        63614192        0.153469
chr16   63614384        63614886        0.119780
chr16   63617333        63618381        0.565214
chr14   43062283        43062785        0.063633
chr14   43168284        43168786        0.086092
chr14   43173091        43173593        0.044918
chr1    189149603       189150142       0.134753
chr17   25919953        25920467        2.496670
chr14   43370304        43370806        0.299451

```
and the `tail` of the BED file is:

```
chr2    117107573       117108075       0.086092
chr2    117087698       117088200       0.093579
chr5    104355328       104355830       0.048661
chr16   63119926        63120428        0.104808
chr16   63129459        63129961        0.168441
chr16   63188180        63188682        0.097322
chr16   63289760        63290296        0.280735
chr16   63363699        63364201        0.101065
chr16   63388149        63388651        0.134753
chr16   63461213        63461715        0.131010
```
These BED files were generated on the output of the commands you posted above.

Thanks for your help!

**Comment by connorrogerson** [comment]
Hi team,

Just wanted to add that I'm getting the same error. I've also used the example FB_enhancer.bed file as input and get the same error.

**Comment by simonvh** [comment]
I think this is a bug on our side. In your environment, can you run the following command and then check again:

```
pip install git+https://github.com/vanheeringen-lab/genomepy@sizes_fix
```

**Comment by mr-ibrahim-ahmed** [comment]
Hi Simon,

I ran the command and it updated genomepy, however I now receive this error:

```
Traceback (most recent call last):
  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/bin/ananse", line 11, in <module>
    from ananse import commands, __version__
  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/lib/python3.7/site-packages/ananse/commands/__init__.py", line 15, in <module>
    "{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], level
  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/lib/python3.7/site-packages/ananse/commands/binding.py", line 12, in <module>
    import ananse.binding
  File "/mnt/fls01-home01/r77887ia/.conda/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 26, in <module>
    from genomepy import Genome
ModuleNotFoundError: No module named 'genomepy'
```
It did uninstall and reinstall a newer `genomepy-0.8.4` as part of your command.

**Comment by simonvh** [comment]
@mr-ibrahim-ahmed did you do that while the conda environmen was activated? Or maybe pip wasn't installed in the environment. Can you try this? (We're also working on an updated version where this bug is fixed)

```
conda activate ananse
conda install pip
pip install git+https://github.com/vanheeringen-lab/genomepy@develop
```

**Comment by mr-ibrahim-ahmed** [comment]
@simonvh Hi Simon, 

Indeed, I had activated the ANANSE environment and `pip` was installed. I've just had a go at removing and recreating the `ananse` environment, however once executing the above code, I get the same error:

` ModuleNotFoundError: No module named 'genomepy'`

Which occurs secondary to:

```
Installing collected packages: genomepy
  Attempting uninstall: genomepy
    Found existing installation: genomepy 0.8.3
    Uninstalling genomepy-0.8.3:
      Successfully uninstalled genomepy-0.8.3
  WARNING: The script genomepy is installed in '/mnt/fls01-home01/r77887ia/gridware/share/python/2.7.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed genomepy-0.8.4
```
when the code is executed. 

Thank you and your team for all your help!!
