### ISSUE TITLE
Ananse influence command

### ISSUE THREAD

**Issue by JoriDeLeuw** [vanheeringen-lab/ANANSE#28]
I found two potential problems when running the command `ananse influence`. The first problem I found was related to the -p tag. When I run for instance this command:
```
ananse influence \
-s /jdeleuw/cell_type1.txt \
-t /jdeleuw/cell_type2.txt \
-d /jdeleuw/degenes.tsv \
-p /jdeleuw/out/type_1VS_type2.pdf \
-o /jdeleuw/out/type_1VS_type2.txt
```
I get the following error message:
```
usage: ananse [-h] <subcommand> [options]
ananse: error: unrecognized arguments: /scratch/bacint/jdeleuw/ananse/ananse_influence/test.pdf
```
I get the same error message when specifying true (`-p true`). 
When I don't specify the path after the -p tag it seems to work fine:
```
ananse influence \
-s /jdeleuw/cell_type1.txt \
-t /jdeleuw/cell_type2.txt \
-d /jdeleuw/degenes.tsv \
-p \
-o /jdeleuw/out/type_1VS_type2.txt
```
I also found a problem related to the documentation. As explanation for the -o tag in the `ananse influence` command, the documentation states "The folder to save results". This should however not be the folder but a txt document as correctly demonstrated in the example of the documentation and in the first two commands of this issue. When I try to specify a folder I get this error message:
```
Matplotlib is building the font cache; this may take a moment.
2021-02-03 11:25:13.047 | INFO     | ananse.influence:__init__:244 - Reading network(s)
2021-02-03 11:49:26.210 | INFO     | ananse.influence:run_influence:338 - Run target score
Traceback (most recent call last):
  File "/mbshome/jdeleuw/miniconda3/envs/ananse/bin/ananse", line 364, in <module>
    args.func(args)
  File "/mbshome/jdeleuw/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/commands/influence.py", line 28, in influence
    a.run_influence(args.plot, args.fin_expression)  # -p and --expression (HGNC gene names and TPM)
  File "/mbshome/jdeleuw/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/influence.py", line 339, in run_influence
    influence_file = self.run_target_score()
  File "/mbshome/jdeleuw/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/influence.py", line 298, in run_target_score
    influence_file = open(self.outfile, "w")
IsADirectoryError: [Errno 21] Is a directory: '/scratch/bacint/jdeleuw/ananse/ananse_influence/test'
```

I am using the version of ananse (0.1.7+1.ge998494), additional information about the environment can be found in the attachment below.
[ananse.txt](https://github.com/vanheeringen-lab/ANANSE/files/5918141/ananse.txt)

**Comment by simonvh** [comment]
Documentation has been updated.
