### ISSUE TITLE
Enhancer command: pandas.errors.EmptyDataError

### ISSUE THREAD

**Issue by andrewbcaldwell** [vanheeringen-lab/ANANSE#32]
Hi,
I am attempting to run ananse enhancer using the hg38 genome (installed with genomepy) for ATAC-seq data. The peaks were called with Genrich and the bam file is sorted. Here is my command:
```
ananse enhancer -g hg38 -t ATAC \
>                   -b NDC.merged.bam \
>                   -p NDC.merged.Genrich.peaks.narrowPeak \
>                   -o NDC.ananse.enhancer.bed
```
and this is the error I get:
```
Could not find/load indexes.

Traceback (most recent call last):
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/bin/ananse", line 364, in <module>
    args.func(args)
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/commands/enhancer.py", line 43, in enhancer
    b.run_enhancer(
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/enhancer.py", line 234, in run_enhancer
    quantile_bed = self.quantileNormalize(epeak, bed_cov, bed_output)
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/enhancer.py", line 215, in quantileNormalize
    bed = pd.read_csv(bed_input, header=None, sep="\t")
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/andrewbcaldwell/miniconda3/envs/ananse/lib/python3.8/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file`
```

**Comment by quan-xu** [comment]
Do you have an index file of the bam file in the same folder?
You can generate an index file with samtools. `samtools index sample.sorted.bam`

**Comment by andrewbcaldwell** [comment]
Thanks, that was the issue!

**Comment by simonvh** [comment]
Updated in the docs to be more explicit.
