### ISSUE TITLE
ananse binding: ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/ANANSE#36]
command:

```
ananse binding -r results_ananse/enhancer/atac_13.25.bed -o results_ananse/binding_13.25.txt -g genomes/UCB_Xtro_10.0/UCB_Xtro_10.0.fa --ncore 8 --pfmfile motif2factors/UCB_Xtro_10.0.gimme.vertebrate.v5.0.pfm --etype ATAC
```

output:

```
2021-02-16 17:58:02.372 | INFO     | ananse.binding:run_binding:253 - Peak initialization
2021-02-16 17:58:02.809 | INFO     | ananse.binding:run_binding:257 - Motif scan
  6%|█████████▋                                                                                                                                                       | 3989/66434 [01:40<03:29, 297.51it/s]100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 66434/66434 [29:13<00:00, 37.88it/s]
2021-02-16 18:27:28.233 | INFO     | ananse.binding:run_binding:261 - Predicting TF binding sites
Traceback (most recent call last):
  File "/vol/mbconda/sande/envs/ananse/bin/ananse", line 364, in <module>
    args.func(args)
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/ananse/commands/binding.py", line 30, in binding
    a.run_binding(args.fin_rpkm, args.outfile)
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 264, in run_binding
    table = self.get_binding_score(pfm, peak)
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/ananse/binding.py", line 245, in get_binding_score
    table["binding"] = clf.predict_proba(table[["zscore", "log10_peakRPKM"]])[:, 1]
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 1651, in predict_proba
    return super()._predict_proba_lr(X)
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 307, in _predict_proba_lr
    prob = self.decision_function(X)
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 268, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "/vol/mbconda/sande/envs/ananse/lib/python3.7/site-packages/sklearn/utils/validation.py", line 586, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required.
```

The files can be found here:
`/scratch/sande/ananse_valueerror/`

I don't know what is going wrong here, if I check my files they look fine to me.. I am running it with my own "custom" motif2factors file, but it looks good to me.. :thinking:

**Comment by Maarten-vd-Sande** [comment]
Definitely related to my motif2factors file, because it works with the default one

**Comment by Maarten-vd-Sande** [comment]
Solved when using command `--unremove-curated`
