### ISSUE TITLE
enhancer command ValueError: Cannot take a larger sample than population when 'replace=False'

### ISSUE THREAD

**Issue by adeben1** [vanheeringen-lab/ANANSE#53]
Command ananse enhancer not working for my data. As genome I used the fasta file of the assembly (my assembly can not be retrieved with genomepy), the folder containing that .fa also stores .fai, .gaps.bed and .sizes files. In addition, the folder containing the .bam file contains the .bai file. The .narrowPeak file was computed with macs2.

Execution command
```
ananse enhancer \
        -g ~/nfur/genome/Nfu_20150522.genes_20140630/Nfu_20150522.softmasked_genome.fa  \
        -t ATAC \
        -b ~/nfur/ATACseq/nucfree/8sem_FB/N-fur-ATAC-8sem-FB1.bam \
        -p ~/nfur/ATACseq/nucfree/8sem_FB/CONS_PEAKS/8sem_FB_rep1_peaks.narrowPeak \
        -o ~/8sem_FB1_enhancer.bed
```

Traceback
```
Traceback (most recent call last):
  File "/home/ska/areyes/miniconda3/envs/ananse/bin/ananse", line 364, in <module>
    args.func(args)
  File "/home/ska/areyes/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/commands/enhancer.py", line 43, in enhancer
    b.run_enhancer(
  File "/home/ska/areyes/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/enhancer.py", line 234, in run_enhancer
    quantile_bed = self.quantileNormalize(epeak, bed_cov, bed_output)
  File "/home/ska/areyes/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/enhancer.py", line 213, in quantileNormalize
    rank = pd.read_csv(self.peak_rank, header=None).sample(n = enahcer_number, random_state = 1).sort_values(0)[0].tolist()
  File "/home/ska/areyes/miniconda3/envs/ananse/lib/python3.8/site-packages/pandas/core/generic.py", line 4995, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 959, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```

**Comment by Maarten-vd-Sande** [comment]
Take a look here: https://github.com/vanheeringen-lab/ANANSE/issues/33
