### ISSUE TITLE
Non-helpfull error region length

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/ANANSE#90]
When running ananse binding with a region file with regions of only 1bp length, the error is not very descriptive:

2021-06-14 16:45:02 | DEBUG | Using default motif file
2021-06-14 16:45:44 | DEBUG | using motifs for 828 factors
2021-06-14 16:45:46 | INFO | Scanning regions for motifs.
2021-06-14 16:45:46,517 - INFO - reading table
2021-06-14 16:46:50,737 - INFO - creating score table (z-score, GC%)
2021-06-14 17:59:30,352 - INFO - done
2021-06-14 17:59:49,052 - INFO - creating dataframe
2021-06-14 18:05:56 | INFO | loading H3K27ac data
2021-06-14 18:21:11 | DEBUG | quantile normalization for H3K27ac
2021-06-14 18:21:13 | INFO | Loading models
2021-06-14 18:21:13 | INFO | 238 models found
2021-06-14 18:21:13 | INFO | Predicting TF activity
2021-06-14 18:22:07,013 - INFO - motif scanning (scores)
2021-06-14 18:22:07,014 - INFO - reading table
2021-06-14 18:23:17,086 - INFO - creating score table (z-score, GC%)
2021-06-14 18:28:41,333 - INFO - done
2021-06-14 18:29:03,692 - INFO - creating dataframe
2021-06-14 18:29:13,310 - INFO - Fitting BayesianRidge
  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/bin/ananse", line 317, in <module>
    args.func(args)
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/binding.py", line 11, in binding
    predict_peaks(
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 697, in predict_peaks
    p.predict_factor_activity(outfile)
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/peakpredictor.py", line 505, in predict_factor_activity
    activity[:] = minmax_scale(activity)
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 545, in minmax_scale
    X = check_array(X, copy=False, ensure_2d=False,
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/mbshome/ibonthuis/miniconda3/envs/ananse/lib/python3.9/site-packages/sklearn/utils/validation.py", line 726, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

I'm rerunning it now in order to see if adjusting region length fixes the issue. Ill comment once I'm sure the region lengths were the problem.

Ideal would be if with smaller region length ananse would resize the regions like some gimme motif tools. Alternatively an more insightfull error would be nice.

:)

**Comment by JGASmits** [comment]
It was indeed the region lenght that was the problem. :)
